name: TREXIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  trexio_ubuntu:

    runs-on: ubuntu-latest
    name: x86 Ubuntu latest

    steps:
      - uses: actions/checkout@v2
    
      - name: install dependencies    
        run: |
          sudo add-apt-repository ppa:kelleyk/emacs
          sudo apt-get install libhdf5-dev emacs26
        
      - name: configure with autotools
        run: |
          ./autogen.sh
          ./configure --enable-maintainer-mode --enable-silent-rules
        
      - name: compile TREXIO
        run: make -j 2
        
      - name: check TREXIO
        run: make check

      - name: create virtual environment
        run: | 
          python3 -m venv --clear pytrexio-venv
          source pytrexio-venv/bin/activate
      
      - name: install Python API
        run: make python-install
        # alternatively we can also run pip install trexio to check PyPI installation

      - name: check Python API
        run: make python-test

      - name: clean
        run: make clean

  trexio_macos:

    runs-on: macos-latest
    name: x86 MacOS latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          brew install emacs
          brew install hdf5
          brew install automake
        
      - name: configure with autotools
        run: |
          ./autogen.sh
          ./configure FC=gfortran-10 --enable-silent-rules --enable-maintainer-mode 
        
      - name: compile TREXIO
        run: make -j 2
        
      - name: check TREXIO
        run: make check
        
      - name: clean
        run: make clean
